export const PASSWORD_SALT = process.env.PASSWORD_SALT;
export const PASSWORD_SALT_ROUNDS = process.env.PASSWORD_SALT_ROUNDS;
export const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
export const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
export const REFRESH_TOKEN_HASH_SECRET = process.env.REFRESH_TOKEN_HASH_SECRET;
